image: node:lts-alpine

cache:
  paths:
    - node_modules

variables:
  PUBLIC_URL: /

stages:
  - deploy

pages:
  stage: deploy
  script:
    - yarn install --production --ignore-optional --pure-lockfile --non-interactive
    - yarn build
    - cp public/index.html public/404.html # Not necessary, but helps with https://medium.com/@pshrmn/demystifying-single-page-applications-3068d0555d46
    - mv public _public # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public # Move build files to public dir for Gitlab Pages
  artifacts:
    paths:
      - public
  only:
    - master
