package pi179$Colecciones;

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

public class Pi183$Colecciones_CuentasUsuarios_Iterator {

	public static void main(String[] args) {
		
		// Creando objetos de tipo Cliente4
		Cliente4 cl1 = new Cliente4("Antonio Banderas", "00001", 200000);
		Cliente4 cl2 = new Cliente4("Rafael Nadal", "00002", 250000);
		Cliente4 cl3 = new Cliente4("Penelope Cruz", "00003", 300000);
		Cliente4 cl4 = new Cliente4("Julio Iglesias", "00004", 300000);
		Cliente4 cl5 = new Cliente4("Antonio Banderas", "00001", 200000); // 'HashSet' no permite duplicados
		
		// Creando colección de tipo 'Set' usando la clase 'HashSet' debido a que esta implementa la interfaz 'Set' // Interfaz Set // Colección de tipo HashSet (Ventajas HashSet: No permite duplicados, Uso sencillo del método add que ademas asegura no elementos duplicados || Inconvenientes: No tiene acceso aleatorio y poca eficiencia a la hora de ordenar elementos)
		Set <Cliente4> ClientesBanco = new HashSet <Cliente4>(); // 'ClientesBanco' será el nombre de la colección // Set es una interfaz y como no se puede instanciar directamente una interfaz se ocupe intanciar la clase 'HashSet' que ya implementa esta interfaz
		
		// Agregando elementos a la colección 
		ClientesBanco.add(cl1); // El método '.add' de la interfaz 'Set' permite agregar elementos del tipo genetico que se especificó antes
		ClientesBanco.add(cl2);
		ClientesBanco.add(cl3);
		ClientesBanco.add(cl4);
		ClientesBanco.add(cl5); // Realmente se imprime en consola lo del 'HashSet' porque apuntan a lugares de memoria completamente diferentes y los toma como si fueran diferentes objetos // Se usarán los métodos 'equals' y 'hashcode' de la clase Object para resolver esto // Ya resuelto sobreeescribiendo los métodos este no aparece
		
		// Quitando un elemento de una colección, como ocurre un problema de concurrencia se cae el programa con una excepción, por esoes mejor usar iteradores para ciertos casos
		/*for (Cliente4 Cliente4 : ClientesBanco) { // bucle 'for each' para mostrar en consola los elementos de la colección // Eclipse autogenerated 'for each' = fore -> SPACE -> ENTER
			if(Cliente4.getNombre().equals("Julio Iglesias")) {
				ClientesBanco.remove(Cliente4);
			}
		}
		for (Cliente4 Cliente4 : ClientesBanco) { // bucle 'for each' para mostrar en consola los elementos de la colección // Eclipse autogenerated 'for each' = fore -> SPACE -> ENTER
			System.out.println(Cliente4.getNombre() + " " + Cliente4.getnCuenta() + " " + Cliente4.getSaldo()); // Saldrán ordenados alfabeticamente según el nombre // La clase 'HashSet' no permite ordenar
		}*/
		
		// Para eliminar objetos es más facil usar un iterador
		Iterator<Cliente4> it = ClientesBanco.iterator(); // Eliminando a "Julio Iglesias" de la colección usando un iterador
		while(it.hasNext()) {
			String nombreCliente = it.next().getNombre();
			if(nombreCliente == "Julio Iglesias") {
				it.remove();
			}
		}
		
		// Para imprimir en consola es más facil usar un bucle ForEach		
		for (Cliente4 Cliente4 : ClientesBanco) { // bucle 'for each' para mostrar en consola los elementos de la colección // Eclipse autogenerated 'for each' = fore -> SPACE -> ENTER
			System.out.println(Cliente4.getNombre() + " " + Cliente4.getnCuenta() + " " + Cliente4.getSaldo()); // Saldrán ordenados alfabeticamente según el nombre // La clase 'HashSet' no permite ordenar
		}
		
		// Haciendo lo mismo que con el ForEach pero con un iterador y solo imprimiendo el nombre
		/*Iterator<Cliente4> it = ClientesBanco.iterator(); // Referencia a la interfaz que recibe un objeto generico de tipo cliente llamado 'it'
		while(it.hasNext()) {	
			String nombreCliente = it.next().getNombre(); // Hay que poner el next() porque no lee el elemento por el que no ha pasado, explicacion en el video 183
			System.out.println(nombreCliente);
		}*/
		
	}

}

class Cliente4 { // AutoGenerate 'getters' and 'setters' in Eclipse: Source -> Generate getters and setters... -> Select all
	
	public Cliente4(String nombre, String nCuenta, double saldo) { // Constructor // Cuando se instancie la clase Cliente4 habrá que especificar estos 3 datos
		this.nombre = nombre; // Almacenando los parámetros en los campos de clase
		this.nCuenta = nCuenta;
		this.saldo = saldo;
	}
	
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getnCuenta() {
		return nCuenta;
	}
	public void setnCuenta(String nCuenta) {
		this.nCuenta = nCuenta;
	}
	public double getSaldo() {
		return saldo;
	}
	public void setSaldo(double saldo) {
		this.saldo = saldo;
	}
	
	// Auto overriding some methods of the superClass Object: Source -> Generate hashCode() and equals() -> Check only nCuenta
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nCuenta == null) ? 0 : nCuenta.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Cliente4 other = (Cliente4) obj;
		if (nCuenta == null) {
			if (other.nCuenta != null)
				return false;
		} else if (!nCuenta.equals(other.nCuenta))
			return false;
		return true;
	}

	private String nombre;
	private String nCuenta;
	private double saldo;
	
}