package pi179$Colecciones;

import java.util.HashSet;
import java.util.Set;

public class Pi181$Colecciones_CuentasUsuarios {

	public static void main(String[] args) {
		
		// Creando objetos de tipo Cliente2
		Cliente2 cl1 = new Cliente2("Antonio Banderas", "00001", 200000);
		Cliente2 cl2 = new Cliente2("Rafael Nadal", "00002", 250000);
		Cliente2 cl3 = new Cliente2("Penelope Cruz", "00003", 300000);
		Cliente2 cl4 = new Cliente2("Julio Iglesias", "00004", 300000);
		Cliente2 cl5 = new Cliente2("Antonio Banderas", "00001", 200000); // 'HashSet' no permite duplicados
		
		// Creando colección de tipo 'Set' usando la clase 'HashSet' debido a que esta implementa la interfaz 'Set' // Interfaz Set // Colección de tipo HashSet (Ventajas HashSet: No permite duplicados, Uso sencillo del método add que ademas asegura no elementos duplicados || Inconvenientes: No tiene acceso aleatorio y poca eficiencia a la hora de ordenar elementos)
		Set <Cliente2> Cliente2sBanco = new HashSet <Cliente2>(); // 'Cliente2sBanco' será el nombre de la colección // Set es una interfaz y como no se puede instanciar directamente una interfaz se ocupe intanciar la clase 'HashSet' que ya implementa esta interfaz
		
		// Agregando elementos a la colección 
		Cliente2sBanco.add(cl1); // El método '.add' de la interfaz 'Set' permite agregar elementos del tipo genetico que se especificó antes
		Cliente2sBanco.add(cl2);
		Cliente2sBanco.add(cl3);
		Cliente2sBanco.add(cl4);
		Cliente2sBanco.add(cl5);
		
		for (Cliente2 Cliente2 : Cliente2sBanco) { // bucle 'for each' para mostrar en consola los elementos de la colección // Eclipse autogenerated 'for each' = fore -> SPACE -> ENTER
			System.out.println(Cliente2.getNombre() + " " + Cliente2.getnCuenta() + " " + Cliente2.getSaldo()); // Saldrán ordenados alfabeticamente según el nombre // La clase 'HashSet' no permite ordenar
		}
		
	}

}

class Cliente2 { // AutoGenerate 'getters' and 'setters' in Eclipse: Source -> Generate getters and setters... -> Select all
	
	public Cliente2(String nombre, String nCuenta, double saldo) { // Constructor // Cuando se instancie la clase Cliente2 habrá que especificar estos 3 datos
		this.nombre = nombre; // Almacenando los parámetros en los campos de clase
		this.nCuenta = nCuenta;
		this.saldo = saldo;
	}
	
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getnCuenta() {
		return nCuenta;
	}
	public void setnCuenta(String nCuenta) {
		this.nCuenta = nCuenta;
	}
	public double getSaldo() {
		return saldo;
	}
	public void setSaldo(double saldo) {
		this.saldo = saldo;
	}

	private String nombre;
	private String nCuenta;
	private double saldo;
	
}